include:
  - services/backend/client-service/docker-compose.yml
  - services/backend/portfolio-service/docker-compose.yml
  - rabbitmq/docker-compose.yml

networks:
  shared-network:
    driver: bridge