name: Check Latest Dependencies
on: [push]
jobs:
    latest_deps:
        name: Latest Dependencies
        runs-on: ubuntu-latest
        continue-on-error: true
        defaults:
            run:
                working-directory: services/backend
        steps:
            - uses: actions/checkout@v3
            - run: rustup update nightly && rustup default nightly
            - run: sudo apt-get update && sudo apt-get install -y sccache
            - run: cargo update
            - run: cargo build
            - run: cargo test